"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import PublicLanding from "./PublicLanding";
import {
  Activity, ArrowDownToLine, ArrowRight, Check, ChevronRight, CircleAlert,
  ClipboardCheck, Database, FileCheck2, FileDown, FileLock2, FileSearch,
  FileText, Fingerprint, Globe2, HelpCircle, KeyRound, LockKeyhole,
  Menu, Plus, RefreshCw, Search, ShieldCheck, ShieldX, UploadCloud,
  Users, X,
} from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
const HOSTED_DEMO = API === "/api";
type Json = Record<string, unknown>;
type AuthUser = { id: string; display_name: string; role: "SENDER" | "RECIPIENT" | "INVESTIGATOR" | "AUDITOR"; recipient_id: string | null; csrf_token: string; expires_at: string };
type Recipient = { id: string; name: string; designation: string; status: string; created_at: string; kem_fingerprint: string; sign_fingerprint: string; kem_public?: string; sign_public?: string; decryption_count?: number };
type Document = { id: string; filename: string; classification: string; uploaded_by: string; created_at: string; status: string; page_count: number; original_hash: string; ciphertext_hash: string; authorized_recipients?: string[]; sessions?: Session[]; recipient_count?: number };
type Session = { id: string; event_id: string; document_id: string; recipient_id: string; created_at: string; marked_hash: string };
type LedgerState = { status: string; quorum: number; total_validators: number; height: number; validators: { validator_id: string; status: string; height: number; reason?: string }[]; replicas_agree?: boolean };
type IndependentState = { status: string; quorum: number; height: number; validator_public_registry_sha3_256: string; validators: { validator_id: string; status: string; reason?: string }[] };
type System = { air_gapped_mode: string; deployment_mode: string; runtime_external_dependencies: number; egress_test: string; pqc_engine: string; watermark_engine: string; ledger: LedgerState; app_version: string; database: string; algorithm_suite?: Json; pqc_error?: string; watermark_error?: string };
type Dashboard = { counts: { documents: number; recipients: number; decryptions: number; ledger_blocks: number; investigations: number }; recent_documents: Document[]; recent_sessions: Session[]; system: System };
type DecryptResult = { session_id: string; event_id: string; recipient_id: string; document_id: string; created_at: string; steps: string[]; ledger: { height: number; quorum: number; block_hash: string }; download_url: string };
type ForensicResult = { investigation_id: string; status: string; reason: string; suspect_sha3_256: string; document_name?: string; session_id?: string; recipient_id?: string; recipient_name?: string; recipient_designation?: string; decrypted_at_utc?: string; watermark?: string; watermark_score?: number; ml_dsa_signature?: string; ledger_chain?: string; validator_quorum?: number; validator_total?: number; ledger_block?: number; block_hash?: string; pipeline: string[] };
type Block = { core: { height: number; created_at_utc: string; previous_block_hash: string; event_hashes: string[]; proposer_id: string }; block_hash: string; validator_approvals: { payload: { validator_id: string } }[]; events: { payload: { event_id: string; recipient_id: string; session_id: string }; signature: string }[] };
type Route = "dashboard" | "documents" | "recipients" | "decrypt" | "ledger" | "forensics" | "system" | "help";
const routes: { key: Route; href: string; en: string; hi: string; icon: typeof Activity }[] = [
  { key: "dashboard", href: "/", en: "Dashboard", hi: "डैशबोर्ड", icon: Activity },
  { key: "documents", href: "/documents", en: "Documents", hi: "दस्तावेज़", icon: FileLock2 },
  { key: "recipients", href: "/recipients", en: "Recipients", hi: "प्राप्तकर्ता", icon: Users },
  { key: "decrypt", href: "/decrypt", en: "Decrypt", hi: "डिक्रिप्ट", icon: KeyRound },
  { key: "ledger", href: "/ledger", en: "Ledger", hi: "लेजर", icon: Database },
  { key: "forensics", href: "/forensics", en: "Forensics", hi: "जांच", icon: FileSearch },
  { key: "system", href: "/system", en: "System", hi: "सिस्टम", icon: Activity },
  { key: "help", href: "/help", en: "Help", hi: "सहायता", icon: HelpCircle },
];
const roleRoutes: Record<AuthUser["role"], Route[]> = {
  SENDER: ["dashboard", "documents", "recipients", "ledger", "system", "help"],
  RECIPIENT: ["dashboard", "documents", "decrypt", "system", "help"],
  INVESTIGATOR: ["dashboard", "forensics", "ledger", "system", "help"],
  AUDITOR: ["dashboard", "recipients", "ledger", "system", "help"],
};
const fmt = (value?: string) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";
const short = (value?: string, n = 14) => value ? `${value.slice(0, n)}…` : "—";
const tone = (value?: string) => /VALID|READY|ACTIVE|HEALTHY|VERIFIED MATCH|CONFIGURED/.test(value || "") ? "good" : /INVALID|ERROR|DIVERGED|REVOKED/.test(value || "") ? "bad" : "warn";

async function call<T>(path: string, init?: RequestInit): Promise<T> {
  let response: Response;
  const mutating = init?.method && init.method !== "GET";
  const headers = new Headers(init?.headers);
  if (mutating && path !== "/auth/login") {
    const csrf = sessionStorage.getItem("sih26237-csrf");
    if (csrf) headers.set("X-CSRF-Token", csrf);
  }
  try { response = await fetch(`${API}${path}`, { cache: "no-store", credentials: "include", ...init, headers }); }
  catch { throw new Error("API unavailable. Please try again shortly."); }
  const data = await response.json().catch(() => ({}));
  if (response.status === 401 && path !== "/auth/login" && path !== "/auth/me") {
    sessionStorage.removeItem("sih26237-csrf");
    window.dispatchEvent(new Event("sourcex-session-expired"));
  }
  if (!response.ok) throw new Error(data.detail || `Request failed (${response.status})`);
  return data as T;
}
const post = <T,>(path: string, body: unknown) => call<T>(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
const Badge = ({ value, className = "" }: { value?: string; className?: string }) => <span className={`badge ${tone(value)} ${className}`}>{value || "UNAVAILABLE"}</span>;
const Hash = ({ value }: { value?: string }) => <code className="hash" title={value}>{short(value, 20)}</code>;
const Empty = ({ title, text }: { title: string; text: string }) => <div className="empty"><FileText size={29}/><strong>{title}</strong><p>{text}</p></div>;

export default function AppShell({ section: _section }: { section?: string }) {
  const pathname = usePathname();
  const router = useRouter();
  const route = (routes.find(r => r.href === pathname)?.key || "dashboard") as Route;
  const [lang, setLang] = useState<"en" | "hi">("en");
  const [auth, setAuth] = useState<AuthUser | null>(null);
  const [authChecked, setAuthChecked] = useState(false);
  const [loginUser, setLoginUser] = useState("sender");
  const [loginPassword, setLoginPassword] = useState("");
  const [loginError, setLoginError] = useState("");
  const [loginBusy, setLoginBusy] = useState(false);
  const [menu, setMenu] = useState(false);
  const [contrast, setContrast] = useState(false);
  const [largeText, setLargeText] = useState(false);
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [recipients, setRecipients] = useState<Recipient[]>([]);
  const [system, setSystem] = useState<System | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [selectedDoc, setSelectedDoc] = useState("");
  const [selectedForDistribution, setSelectedForDistribution] = useState<string[]>([]);
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [classification, setClassification] = useState("DEMO RESTRICTED");
  const [query, setQuery] = useState("");
  const [classFilter, setClassFilter] = useState("ALL");
  const [sort, setSort] = useState("newest");
  const [recipientName, setRecipientName] = useState("");
  const [recipientDesignation, setRecipientDesignation] = useState("");
  const [recipientPassword, setRecipientPassword] = useState("");
  const [publicKey, setPublicKey] = useState<Recipient | null>(null);
  const [decryptResult, setDecryptResult] = useState<DecryptResult | null>(null);
  const [forensicFile, setForensicFile] = useState<File | null>(null);
  const [forensicResult, setForensicResult] = useState<ForensicResult | null>(null);
  const [blocks, setBlocks] = useState<Block[]>([]);
  const [ledger, setLedger] = useState<LedgerState | null>(null);
  const [independent, setIndependent] = useState<IndependentState | null>(null);
  const [selectedBlock, setSelectedBlock] = useState<number | null>(null);
  const [robustness, setRobustness] = useState<{ transformation: string; status: string; score?: number; matched_session_id?: string }[] | null>(null);
  const [eventVerification, setEventVerification] = useState<Record<string, { status: string; signature: string; ledger: string; quorum: number }>>({});

  const refresh = useCallback(async () => {
    try {
      const [dash, docs, people, sys] = await Promise.all([
        call<Dashboard>("/dashboard"), call<Document[]>("/documents"),
        call<Recipient[]>("/recipients"), call<System>("/system/status"),
      ]);
      setDashboard(dash); setDocuments(docs); setRecipients(people); setSystem(sys); setError("");
      setSelectedDoc(old => old || docs[0]?.id || "");
      if (!selectedForDistribution.length) setSelectedForDistribution(people.filter(p => p.status === "ACTIVE").map(p => p.id));
    } catch (e) { setError((e as Error).message); }
  }, [selectedForDistribution.length]);

  useEffect(() => {
    void call<AuthUser | null>("/auth/me").then(user => {
      if (user) {
        sessionStorage.setItem("sih26237-csrf", user.csrf_token);
        setAuth(user);
      } else {
        sessionStorage.removeItem("sih26237-csrf");
      }
    }).catch(() => { sessionStorage.removeItem("sih26237-csrf"); }).finally(() => setAuthChecked(true));
  }, []);
  useEffect(() => { if (auth) void refresh(); }, [auth, refresh]);
  useEffect(() => {
    const expired = () => {
      setAuth(null); setDashboard(null); setDocuments([]); setRecipients([]);
      setDecryptResult(null); setForensicResult(null); setBlocks([]);
      setLoginError("Session expired. Sign in again to continue.");
      router.push("/");
    };
    window.addEventListener("sourcex-session-expired", expired);
    return () => window.removeEventListener("sourcex-session-expired", expired);
  }, [router]);
  const signIn = async () => {
    setLoginBusy(true); setLoginError("");
    try {
      const user = await post<AuthUser>("/auth/login", { user_id: loginUser, password: loginPassword });
      sessionStorage.setItem("sih26237-csrf", user.csrf_token);
      setAuth(user); setLoginPassword(""); router.push("/");
    } catch (e) { setLoginError((e as Error).message); }
    finally { setLoginBusy(false); }
  };
  const signOut = async () => {
    try { await post("/auth/logout", {}); } catch { /* Clear local state even if session expired. */ }
    sessionStorage.removeItem("sih26237-csrf");
    setAuth(null); setDashboard(null); setDocuments([]); setRecipients([]); setForensicResult(null);
    setDecryptResult(null); setBlocks([]); setError(""); router.push("/");
  };
  const action = async (work: () => Promise<void>) => {
    setBusy(true); setError(""); setNotice("");
    try { await work(); await refresh(); }
    catch (e) { setError((e as Error).message); }
    finally { setBusy(false); }
  };
  const go = (href: string) => { setMenu(false); router.push(href); };
  const current = routes.find(r => r.key === route)!;
  const filteredDocs = useMemo(() => documents.filter(d =>
    d.filename.toLowerCase().includes(query.toLowerCase()) && (classFilter === "ALL" || d.classification === classFilter)
  ).sort((a, b) => sort === "oldest" ? a.created_at.localeCompare(b.created_at) : b.created_at.localeCompare(a.created_at)), [documents, query, classFilter, sort]);
  const allSessions = dashboard?.recent_sessions || [];
  const allowedRoutes = auth ? roleRoutes[auth.role] : [];
  const activeRoute = allowedRoutes.includes(route) ? route : null;
  const canOperate = !busy && system?.pqc_engine === "READY" && system?.watermark_engine === "READY";

  if (!authChecked) return <div className="auth-loading" role="status"><span className="auth-loading-mark"><ShieldCheck size={30}/></span><strong>SourceX</strong><span>Checking session…</span><span className="auth-loading-bar" aria-hidden="true"/></div>;
  if (!auth) return <PublicLanding loginUser={loginUser} setLoginUser={setLoginUser} loginPassword={loginPassword} setLoginPassword={setLoginPassword} loginError={loginError} loginBusy={loginBusy} onSignIn={() => void signIn()}/>;

  return <div className={`site ${contrast ? "high-contrast" : ""} ${largeText ? "large-text" : ""}`}>
    <a className="skip-link" href="#main">Skip to main content</a>
    <div className="gov-strip"><div className="container strip-inner"><span>भारत सरकार <span className="strip-divider">|</span> Government of India</span><div className="strip-tools"><button onClick={() => setLang(lang === "en" ? "hi" : "en")} aria-label="Change interface language"><Globe2 size={13}/> {lang === "en" ? "हिन्दी" : "English"}</button><button onClick={() => setLargeText(!largeText)} aria-label="Toggle larger text">A{largeText ? "−" : "+"}</button><button onClick={() => setContrast(!contrast)} aria-label="Toggle high contrast">◐</button></div></div></div>
    <header className="masthead"><div className="container masthead-inner"><div className="brand-mark" aria-hidden="true"><ShieldCheck size={27}/></div><div className="brand-copy"><span className="brand-overline">SIH 2026 · Ministry of Defence problem statement</span><strong>SourceX</strong><span className="brand-sub">Cryptographic attribution demonstrator</span></div><div className="header-right"><span className="prototype-pill">RESEARCH PROTOTYPE</span><div className="persona-wrap"><span className="account-label">SIGNED IN · {auth.role}</span><strong className="account-name">{auth.display_name}</strong><button className="inline-button" onClick={() => void signOut()}>Sign out</button></div></div><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Open navigation">{menu ? <X/> : <Menu/>}</button></div></header>
    <div className="prototype-warning"><div className="container"><CircleAlert size={15}/> SIH 2026 Prototype — Not an official Ministry of Defence deployment. Synthetic documents only.</div></div>
    <nav className={`nav ${menu ? "open" : ""}`} aria-label="Primary navigation"><div className="container nav-inner">{routes.filter(item => allowedRoutes.includes(item.key)).map(item => { const Icon = item.icon; return <button key={item.key} className={route === item.key ? "active" : ""} onClick={() => go(item.href)}><Icon size={17}/><span>{lang === "en" ? item.en : item.hi}</span></button>; })}<button className="mobile-signout" onClick={() => void signOut()}>Sign out</button></div></nav>
    <main id="main" className="container main"><div className="breadcrumbs"><button onClick={() => go("/")}>Home</button><ChevronRight size={13}/><span>{lang === "en" ? current.en : current.hi}</span></div>
      {busy && <div className="operation-progress" role="status" aria-live="polite"><span className="operation-spinner" aria-hidden="true"/> Processing and verifying evidence…</div>}
      {error && <div className="alert error" role="alert"><ShieldX size={18}/><span>{error}</span><button onClick={() => setError("")} aria-label="Dismiss error"><X size={16}/></button></div>}
      {notice && <div className="alert success" role="status"><Check size={18}/><span>{notice}</span><button onClick={() => setNotice("")} aria-label="Dismiss notice"><X size={16}/></button></div>}
      {!activeRoute && <section className="panel access-denied"><ShieldX size={30}/><h1>Access restricted</h1><p>{auth.display_name} cannot open this workspace. Choose a permitted section from the navigation.</p><button className="button primary" onClick={() => go("/")}>Return to dashboard</button></section>}
      {activeRoute === "dashboard" && <>
        <section className="hero"><div><span className="eyebrow">SECURE DISTRIBUTION · VERIFIED PROVENANCE</span><h1>One encrypted document.<br/><em>Every copy accountable.</em></h1><p>Distribute a PDF once, issue recipient-specific decryptions, and investigate a suspected leak through visual watermarking, post-quantum signatures and a replicated tamper-evident ledger.</p><div className="hero-actions">{auth.role === "SENDER" && <button className="button primary" onClick={() => go("/documents")}>Distribute a document <ArrowRight size={17}/></button>}{auth.role === "RECIPIENT" && <button className="button primary" onClick={() => go("/decrypt")}>Open my document <ArrowRight size={17}/></button>}{auth.role === "INVESTIGATOR" && <button className="button primary" onClick={() => go("/forensics")}>Analyze a found PDF <ArrowRight size={17}/></button>}{auth.role === "AUDITOR" && <button className="button primary" onClick={() => go("/ledger")}>Verify the ledger <ArrowRight size={17}/></button>}</div></div><div className="hero-graphic" aria-label="Encryption, recipient and ledger flow"><div className="flow-node source"><FileLock2 size={25}/><span>ENCRYPT ONCE</span></div><div className="flow-line"/><div className="flow-people"><span>REC-001</span><span>REC-002</span><span>REC-003</span></div><div className="flow-line"/><div className="flow-node"><Fingerprint size={24}/><span>ATTRIBUTABLE COPIES</span></div></div></section>
        <div className="status-ribbon"><span className="status-title"><span className="pulse"/> SYSTEM STATUS</span><span><b>{HOSTED_DEMO ? "HOSTED DEMO" : "AIR-GAPPED MODE"}</b> {HOSTED_DEMO ? "TEMPORARY STORAGE" : (system?.air_gapped_mode || "UNAVAILABLE")}</span><span><b>PQC</b> <Badge value={system?.pqc_engine}/></span><span><b>VALIDATORS</b> {system?.ledger.quorum ?? "—"}/3</span><span><b>WATERMARK</b> <Badge value={system?.watermark_engine}/></span></div>
        <div className="section-head"><div><span className="eyebrow">OPERATIONS OVERVIEW</span><h2>Dashboard</h2></div><button className="text-button" onClick={() => void refresh()}><RefreshCw size={16}/> Refresh</button></div>
        <div className="metric-grid">{[["Protected documents", dashboard?.counts.documents, FileLock2], ["Authorized recipients", dashboard?.counts.recipients, Users], ["Successful decryptions", dashboard?.counts.decryptions, KeyRound], ["Ledger blocks", dashboard?.counts.ledger_blocks, Database], ["Investigations", dashboard?.counts.investigations, FileSearch], ["Validator quorum", system ? `${system.ledger.quorum}/3` : "—", ShieldCheck]].map(([label, value, Icon], index) => { const I = Icon as typeof Activity; return <div className="metric" key={index}><div className="metric-icon"><I size={20}/></div><span>{label as string}</span><strong>{String(value ?? "—")}</strong></div>; })}</div>
        <div className="two-column"><section className="panel"><div className="panel-head"><div><span className="eyebrow">LATEST ACTIVITY</span><h3>Recent decryptions</h3></div>{allowedRoutes.includes("ledger") && <button className="text-button" onClick={() => go("/ledger")}>View ledger <ArrowRight size={15}/></button>}</div>{allSessions.length ? <div className="activity-list">{allSessions.map(s => <div className="activity-item" key={s.id}><span className="activity-icon"><FileCheck2 size={17}/></span><div><strong>{s.recipient_id} decrypted a document</strong><small>Session {short(s.id, 8)} · {fmt(s.created_at)}</small></div><Badge value={system?.ledger.status}/></div>)}</div> : <Empty title="No decryptions yet" text="Distribute a document, then decrypt it as a recipient."/>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">TRUST NETWORK</span><h3>Ledger health</h3></div><Badge value={system?.ledger.status}/></div><div className="validator-list">{(system?.ledger.validators || []).map(v => <div key={v.validator_id}><span className={`node-dot ${tone(v.status)}`}/><span>{v.validator_id}</span><Badge value={v.status}/></div>)}</div><div className="panel-foot"><span>Consensus threshold</span><strong>2 of 3 approvals</strong></div></section></div>
        <section className="panel crypto-panel"><div><span className="eyebrow">STANDARDS-BASED RESEARCH PROTOTYPE</span><h3>Cryptographic suite</h3><p>Actual cryptographic operations run in the Python service. The local edition can run without external network services.</p></div><div className="suite-grid"><span>Content encryption <strong>AES-256-GCM</strong></span><span>Key establishment <strong>ML-KEM-768</strong></span><span>Recipient signature <strong>ML-DSA-65</strong></span><span>Hashing <strong>SHA3-256</strong></span></div></section>
      </>}
      {activeRoute === "documents" && <><PageTitle eyebrow={auth.role === "SENDER" ? "DOCUMENT AUTHORITY" : "RECIPIENT WORKSPACE"} title={auth.role === "SENDER" ? "Documents & distribution" : "Documents addressed to you"} description={auth.role === "SENDER" ? "Encrypt a PDF once, then create a separate post-quantum key envelope for each authorized recipient." : "Only documents with an envelope for your signed-in identity appear here."}/>
        {auth.role === "SENDER" && <div className="two-column docs-top"><section className="panel"><div className="panel-head"><div><span className="eyebrow">NEW PROTECTED DOCUMENT</span><h3>Upload PDF</h3></div><UploadCloud size={21}/></div><div className="field"><label htmlFor="pdf-upload">PDF document (up to 15 MB, 12 pages)</label><input id="pdf-upload" type="file" accept="application/pdf,.pdf" onChange={e => setUploadFile(e.target.files?.[0] || null)}/></div><div className="field"><label htmlFor="classification">Demo classification</label><select id="classification" value={classification} onChange={e => setClassification(e.target.value)}><option>OFFICIAL</option><option>DEMO RESTRICTED</option><option>CONFIDENTIAL — DEMO ONLY</option></select></div><button className="button primary" disabled={!uploadFile || !canOperate} onClick={() => void action(async () => { const form = new FormData(); form.append("file", uploadFile!); form.append("classification", classification); const doc = await call<Document>("/documents", { method: "POST", body: form }); setSelectedDoc(doc.id); setUploadFile(null); (document.getElementById("pdf-upload") as HTMLInputElement).value = ""; setNotice("Document encrypted once with AES-256-GCM. Select recipients below."); })}>Encrypt & add document <ArrowRight size={16}/></button></section>
        <section className="panel"><div className="panel-head"><div><span className="eyebrow">AUTHORIZE RECIPIENTS</span><h3>Distribute securely</h3></div><KeyRound size={21}/></div><div className="field"><label htmlFor="distribute-doc">Protected document</label><select id="distribute-doc" value={selectedDoc} onChange={e => setSelectedDoc(e.target.value)}>{documents.map(d => <option key={d.id} value={d.id}>{d.filename}</option>)}</select></div><div className="field"><span className="field-label">Recipients</span><div className="checkbox-list">{recipients.filter(p => p.status === "ACTIVE").map(p => <label key={p.id}><input type="checkbox" checked={selectedForDistribution.includes(p.id)} onChange={e => setSelectedForDistribution(e.target.checked ? [...selectedForDistribution, p.id] : selectedForDistribution.filter(id => p.id !== id))}/><span>{p.name}<small>{p.id} · {p.designation}</small></span></label>)}</div></div><button className="button primary" disabled={!selectedDoc || !selectedForDistribution.length || !canOperate} onClick={() => void action(async () => { const result = await post<{ envelope_count: number; content_encryption_count: number }>(`/documents/${selectedDoc}/distribute`, { recipient_ids: selectedForDistribution }); setNotice(`${result.envelope_count} ML-KEM envelopes created. The PDF ciphertext was produced ${result.content_encryption_count} time.`); })}>Create recipient envelopes <ArrowRight size={16}/></button></section></div>}
        <section className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">DOCUMENT REGISTER</span><h3>Protected documents</h3></div><span className="muted">{filteredDocs.length} records</span></div><div className="table-tools"><label className="search-box"><Search size={17}/><input aria-label="Search documents" placeholder="Search documents" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Filter classification" value={classFilter} onChange={e => setClassFilter(e.target.value)}><option value="ALL">All classifications</option><option>OFFICIAL</option><option>DEMO RESTRICTED</option><option>CONFIDENTIAL — DEMO ONLY</option></select><select aria-label="Sort documents" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></div>{filteredDocs.length ? <div className="table-wrap"><table><thead><tr><th>Document</th><th>Classification</th><th>Created</th><th>Pages</th><th>Status</th><th>Action</th></tr></thead><tbody>{filteredDocs.map(d => <tr key={d.id}><td><strong>{d.filename}</strong><small>{short(d.id, 12)}</small></td><td>{d.classification}</td><td>{fmt(d.created_at)}</td><td>{d.page_count}</td><td><Badge value={d.status}/></td><td><button className="inline-button" onClick={() => void action(async () => { const detail = await call<Document>(`/documents/${d.id}`); setSelectedDoc(d.id); setNotice(`${d.filename}: ${detail.authorized_recipients?.length || 0} authorized recipients, ${detail.sessions?.length || 0} decryptions. SHA3-256 ${short(detail.original_hash, 20)}`); })}>Details</button></td></tr>)}</tbody></table></div> : <Empty title="No matching documents" text="Upload a synthetic PDF or adjust your search."/>}</section>
      </>}
      {activeRoute === "recipients" && <><PageTitle eyebrow="IDENTITY REGISTRY" title="Authorized recipients" description="Each fictional demo identity has a separate ML-KEM-768 encryption key and ML-DSA-65 signing key."/>
        {auth.role === "SENDER" && <section className="panel create-recipient"><div><span className="eyebrow">ADD DEMO IDENTITY</span><h3>Generate recipient</h3><p>New keys are generated locally. Set a password and share it directly with this fictional recipient.</p></div><div className="field"><label htmlFor="recipient-name">Full name</label><input id="recipient-name" value={recipientName} onChange={e => setRecipientName(e.target.value)} placeholder="Fictional recipient name"/></div><div className="field"><label htmlFor="recipient-designation">Designation</label><input id="recipient-designation" value={recipientDesignation} onChange={e => setRecipientDesignation(e.target.value)} placeholder="Demo designation"/></div><div className="field"><label htmlFor="recipient-password">Account password (10+ characters)</label><input id="recipient-password" type="password" value={recipientPassword} onChange={e => setRecipientPassword(e.target.value)} autoComplete="new-password"/></div><button className="button primary" disabled={busy || recipientName.trim().length < 2 || recipientDesignation.trim().length < 2 || recipientPassword.length < 10} onClick={() => void action(async () => { const p = await post<Recipient>("/recipients", { name: recipientName, designation: recipientDesignation, password: recipientPassword }); setNotice(`${p.id} generated with post-quantum keypairs and a recipient login.`); setRecipientName(""); setRecipientDesignation(""); setRecipientPassword(""); })}><Plus size={16}/> Generate</button></section>}
        <div className="recipient-grid">{recipients.map(p => <article className="panel recipient-card" key={p.id}><div className="recipient-head"><div className="avatar">{p.name.split(" ").map(x => x[0]).slice(0, 2).join("")}</div><Badge value={p.status}/></div><span className="eyebrow">{p.id}</span><h3>{p.name}</h3><p>{p.designation}</p><div className="key-list"><div><span>ML-KEM-768</span><Hash value={p.kem_fingerprint}/></div><div><span>ML-DSA-65</span><Hash value={p.sign_fingerprint}/></div></div><div className="card-actions"><button className="inline-button" onClick={() => setPublicKey(p)}>View public keys</button>{auth.role === "SENDER" && p.status === "ACTIVE" && <button className="inline-button danger" disabled={busy} onClick={() => void action(async () => { await post(`/recipients/${p.id}/revoke`, {}); setNotice(`${p.id} revoked. New decryptions are blocked.`); })}>Revoke</button>}</div></article>)}</div>
        {publicKey && <div className="modal-backdrop" onClick={() => setPublicKey(null)}><div className="modal" role="dialog" aria-modal="true" aria-label="Public key details" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setPublicKey(null)} aria-label="Close"><X/></button><span className="eyebrow">PUBLIC CRYPTOGRAPHIC IDENTITY</span><h2>{publicKey.name}</h2><p>Public keys can be shared. Private keys remain sealed in local demo storage.</p><div className="key-detail"><strong>ML-KEM-768 fingerprint</strong><code>{publicKey.kem_fingerprint}</code><strong>ML-DSA-65 fingerprint</strong><code>{publicKey.sign_fingerprint}</code><strong>ML-KEM public key (Base64)</strong><code>{publicKey.kem_public}</code><strong>ML-DSA public key (Base64)</strong><code>{publicKey.sign_public}</code></div></div></div>}
      </>}
      {activeRoute === "decrypt" && <><PageTitle eyebrow="RECIPIENT WORKSPACE" title="Decrypt & claim a copy" description="Every successful decryption creates a new image-only PDF, unique rendered watermark, signed event and ledger block. The source remains encrypted."/>
        <div className="two-column"><section className="panel"><div className="panel-head"><div><span className="eyebrow">AUTHORIZED ACCESS</span><h3>New decryption session</h3></div><LockKeyhole size={24}/></div><div className="field"><span className="field-label">Signed-in recipient</span><strong>{auth.recipient_id} · {auth.display_name}</strong></div><div className="field"><label htmlFor="decrypt-doc">Document addressed to you</label><select id="decrypt-doc" value={selectedDoc} onChange={e => setSelectedDoc(e.target.value)}>{documents.map(d => <option key={d.id} value={d.id}>{d.filename}</option>)}</select></div><div className="explain"><KeyRound size={17}/><p>Your account can recover only its own ML-KEM envelope. The API binds every decryption request to your signed-in identity.</p></div><button className="button primary" disabled={!selectedDoc || !auth.recipient_id || !canOperate} onClick={() => void action(async () => { const result = await post<DecryptResult>("/decrypt", { document_id: selectedDoc, recipient_id: auth.recipient_id }); setDecryptResult(result); setNotice("Decryption signed and committed. Your marked PDF is ready."); })}>Decrypt & commit event <ArrowRight size={17}/></button></section>
        <section className="panel process-panel"><span className="eyebrow">CRYPTOGRAPHIC PATH</span><h3>What happens on access</h3><ol className="step-list"><li><span>01</span> ML-KEM-768 recovers the shared content key</li><li><span>02</span> AES-256-GCM authenticates and decrypts the PDF</li><li><span>03</span> A fresh visual watermark marks rendered content</li><li><span>04</span> ML-DSA-65 signs the canonical event</li><li><span>05</span> Three validators approve a linked ledger block</li></ol></section></div>
        {decryptResult && <section className="panel result-panel"><div><span className="eyebrow">SESSION COMMITTED</span><h3>Recipient copy ready</h3><p>Session <Hash value={decryptResult.session_id}/> · block #{decryptResult.ledger.height} · quorum {decryptResult.ledger.quorum}/3</p><div className="step-chips">{decryptResult.steps.map(s => <span key={s}><Check size={13}/>{s}</span>)}</div><p className="fine-print">Issued pages are image-only, which removes simple text selection. Screenshots, OCR and retyping can still reproduce content without its watermark.</p></div><div className="result-actions"><a className="button primary" href={`${API}${decryptResult.download_url}`} download>Download marked PDF <ArrowDownToLine size={17}/></a><span className="muted">A found copy can later be uploaded by the investigator account.</span></div></section>}
      </>}
      {activeRoute === "forensics" && <><PageTitle eyebrow="FORENSIC INVESTIGATION" title="Trace a suspected copy" description="Upload a PDF. The detector reads visual content, then independently verifies the signed session and validator ledger."/>
        <div className="two-column forensic-top"><section className="panel"><div className="panel-head"><div><span className="eyebrow">SUSPECT DOCUMENT</span><h3>Analyze a PDF</h3></div><FileSearch size={24}/></div><label className="drop-area" htmlFor="forensic-file"><UploadCloud size={35}/><strong>{forensicFile?.name || "Choose a suspected leaked PDF"}</strong><span>PDF only · max 15 MB · selected digital transformations supported</span><input id="forensic-file" type="file" accept="application/pdf,.pdf" onChange={e => setForensicFile(e.target.files?.[0] || null)}/></label><button className="button primary" disabled={!forensicFile || !canOperate} onClick={() => void action(async () => { const form = new FormData(); form.append("file", forensicFile!); const result = await call<ForensicResult>("/forensics/analyze", { method: "POST", body: form }); setForensicResult(result); setNotice(result.status === "VERIFIED MATCH" ? "Visual and cryptographic evidence verified." : result.reason); })}>Run forensic analysis <ArrowRight size={17}/></button></section><section className="panel"><span className="eyebrow">EVIDENCE PIPELINE</span><h3>Independent checks</h3><ol className="step-list forensic-steps">{["SHA3-256 file hash", "PDF pages rendered", "Visual carrier detected", "Session reconstructed", "ML-DSA-65 signature verified", "Hash chain & quorum verified"].map((s, i) => <li key={s}><span>{String(i + 1).padStart(2, "0")}</span>{s}</li>)}</ol></section></div>
        {forensicResult && <section className={`forensic-result ${forensicResult.status === "VERIFIED MATCH" ? "verified" : "unverified"}`}><div className="forensic-banner"><div><span className="eyebrow">FORENSIC ATTRIBUTION</span><h2>{forensicResult.status === "VERIFIED MATCH" ? <><ShieldCheck size={34}/> VERIFIED MATCH</> : <><CircleAlert size={34}/> {forensicResult.status}</>}</h2><p>{forensicResult.reason}</p></div><span>INVESTIGATION<br/><strong>{short(forensicResult.investigation_id, 8)}</strong></span></div>{forensicResult.status === "VERIFIED MATCH" ? <><div className="evidence-grid"><Evidence label="ATTRIBUTED RECIPIENT" value={`${forensicResult.recipient_id} · ${forensicResult.recipient_name}`} detail={forensicResult.recipient_designation}/><Evidence label="DOCUMENT" value={forensicResult.document_name}/><Evidence label="DECRYPTION SESSION" value={short(forensicResult.session_id, 24)} detail={fmt(forensicResult.decrypted_at_utc)}/><Evidence label="VISUAL WATERMARK" value={forensicResult.watermark} detail={`Correlation score ${forensicResult.watermark_score?.toFixed(3)} · not a probability`}/><Evidence label="ML-DSA-65 SIGNATURE" value={forensicResult.ml_dsa_signature}/><Evidence label="LEDGER / VALIDATORS" value={`${forensicResult.ledger_chain} · ${forensicResult.validator_quorum}/${forensicResult.validator_total}`} detail={`Block #${forensicResult.ledger_block}`}/></div><div className="forensic-foot"><div><span>Block hash</span><Hash value={forensicResult.block_hash}/></div><div className="result-actions"><a className="button secondary" href={`${API}/forensics/${forensicResult.investigation_id}/report.json`} download><FileDown size={17}/> JSON report</a><a className="button secondary" href={`${API}/forensics/${forensicResult.investigation_id}/report.html`} target="_blank" rel="noreferrer"><FileText size={17}/> Print report</a></div></div></> : <div className="inconclusive"><p>No recipient is attributed when the evidence is below threshold or verification fails.</p><Hash value={forensicResult.suspect_sha3_256}/></div>}</section>}
        <section className="panel lab-panel"><div className="panel-head"><div><span className="eyebrow">EXTRA FEATURE — NOT EXPLICITLY REQUIRED BY SIH26237</span><h3>Watermark robustness lab</h3><p>Analyze a marked copy first, then test that session under local digital transformations.</p></div></div><div className="lab-controls"><span>{forensicResult?.session_id ? `Session ${short(forensicResult.session_id, 20)}` : "No matched session yet"}</span><button className="button secondary" disabled={busy || !forensicResult?.session_id} onClick={() => void action(async () => { setRobustness(await call(`/sessions/${forensicResult!.session_id}/robustness`)); })}>Run digital transforms</button></div>{robustness && <div className="table-wrap"><table><thead><tr><th>Transformation</th><th>Detection</th><th>Correlation score</th><th>Matched session</th></tr></thead><tbody>{robustness.map(r => <tr key={r.transformation}><td>{r.transformation}</td><td><Badge value={r.status}/></td><td>{r.score?.toFixed(3) ?? "—"}</td><td><Hash value={r.matched_session_id}/></td></tr>)}</tbody></table></div>}<p className="fine-print">The text-only reconstruction is a negative control and should be INCONCLUSIVE: visual evidence cannot survive retyping. Digital shift, rotation, compression and scaling are measured in the local benchmark. Physical print/scan requires further evaluation.</p></section>
      </>}
      {activeRoute === "ledger" && <><PageTitle eyebrow="PERMISSIONED AUDIT CHAIN" title="Ledger explorer" description="Three local validator stores hold independently signed, hash-linked blocks. Two approvals establish quorum."/>
        <div className="ledger-toolbar"><div><Badge value={ledger?.status || system?.ledger.status}/><span>Validator quorum <strong>{ledger?.quorum ?? system?.ledger.quorum ?? "—"}/3</strong></span></div><button className="button primary" disabled={busy} onClick={() => void action(async () => { const result = await post<LedgerState>("/ledger/verify", {}); setLedger(result); setBlocks(await call<Block[]>("/ledger/blocks")); setNotice(result.status === "VALID" ? `Chain verified with ${result.quorum}/3 matching validators.` : "Ledger verification reported a failure."); })}><ClipboardCheck size={17}/> Verify entire chain</button></div>
        <section className="panel"><div className="panel-head"><div><span className="eyebrow">SECOND VERIFICATION PATH</span><h3>Read-only public-key verifier</h3><p>A separate Python process reads all three replicas and checks hashes and signatures without private keys.</p></div><button className="button secondary" disabled={busy} onClick={() => void action(async () => { setIndependent(await post<IndependentState>("/ledger/independent-verify", {})); })}>Run independent check</button></div>{independent && <div className="validator-list"><Badge value={independent.status}/><span>Matching replicas {independent.quorum}/3 · height {independent.height}</span><span>Public registry SHA3-256 <Hash value={independent.validator_public_registry_sha3_256}/></span>{independent.validators.map(node => <div key={node.validator_id}><span>{node.validator_id}</span><Badge value={node.status}/>{node.reason && <small>{node.reason}</small>}</div>)}</div>}<p className="fine-print">Separate verifier process on this machine; validator keys and storage remain under one host administrator.</p></section>
        <div className="two-column ledger-layout"><section className="panel"><div className="panel-head"><div><span className="eyebrow">BLOCKS</span><h3>Authoritative chain</h3></div><button className="text-button" onClick={() => void action(async () => { setBlocks(await call<Block[]>("/ledger/blocks")); setLedger(await call<LedgerState>("/ledger/validators")); })}><RefreshCw size={15}/> Load blocks</button></div>{blocks.length ? <div className="block-list">{blocks.slice().reverse().map(b => <button key={b.core.height} className={`block-card ${selectedBlock === b.core.height ? "selected" : ""}`} onClick={() => setSelectedBlock(b.core.height)}><span className="block-number">BLOCK #{String(b.core.height).padStart(6, "0")}</span><span>{fmt(b.core.created_at_utc)}</span><Hash value={b.block_hash}/><small>{b.core.event_hashes.length} event(s) · {b.validator_approvals.length}/3 signatures</small></button>)}</div> : <Empty title="Load ledger blocks" text="Select Load blocks to inspect the hash chain."/>}</section><section className="panel block-detail"><span className="eyebrow">BLOCK DETAIL</span>{selectedBlock !== null && blocks.find(b => b.core.height === selectedBlock) ? (() => { const b = blocks.find(x => x.core.height === selectedBlock)!; return <><h3>Block #{String(b.core.height).padStart(6, "0")}</h3><dl><dt>Timestamp</dt><dd>{fmt(b.core.created_at_utc)}</dd><dt>Previous hash</dt><dd><code>{b.core.previous_block_hash}</code></dd><dt>Block hash</dt><dd><code>{b.block_hash}</code></dd><dt>Proposer</dt><dd>{b.core.proposer_id}</dd><dt>Event hashes</dt><dd>{b.core.event_hashes.length ? b.core.event_hashes.map(id => <code key={id}>{id}</code>) : "Genesis block"}</dd><dt>Validator approvals</dt><dd>{b.validator_approvals.map(a => <Badge key={a.payload.validator_id} value={a.payload.validator_id}/>)}</dd></dl>{b.events.map(event => <div className="ledger-event" key={event.payload.event_id}><strong>Decryption event {short(event.payload.event_id, 18)}</strong><span>{event.payload.recipient_id} · session {short(event.payload.session_id, 12)}</span><button className="button secondary" disabled={busy} onClick={() => void action(async () => { const verified = await post<{ status: string; signature: string; ledger: string; quorum: number }>(`/events/${event.payload.event_id}/verify`, {}); setEventVerification(old => ({ ...old, [event.payload.event_id]: verified })); })}>Verify signature</button>{eventVerification[event.payload.event_id] && <div><Badge value={eventVerification[event.payload.event_id].signature}/><span> Ledger {eventVerification[event.payload.event_id].ledger} · quorum {eventVerification[event.payload.event_id].quorum}/3</span></div>}</div>)}</>; })() : <p className="muted">Select a block to inspect signed approvals and linked hashes.</p>}</section></div>
        <section className="panel tamper-panel"><div><span className="eyebrow">EXTRA FEATURE — NOT EXPLICITLY REQUIRED BY SIH26237</span><h3>Demonstration-only tamper test</h3><p>Corrupt validator-2’s local copy and independently verify the remaining 2-of-3 authoritative chain. Restore it afterward.</p></div><div className="tamper-actions"><button className="button outline-danger" disabled={busy || (system?.ledger.height || 0) < 1} onClick={() => void action(async () => { setLedger(await post<LedgerState>("/demo/tamper-validator", { validator_id: "validator-2" })); setNotice("DEMONSTRATION ONLY: validator-2 diverged. Check verifier status."); })}>Tamper validator-2</button><button className="button secondary" disabled={busy} onClick={() => void action(async () => { setLedger(await post<LedgerState>("/demo/restore-validator", { validator_id: "validator-2" })); setNotice("Validator-2 restored from the matching quorum chain."); })}>Restore validator-2</button></div></section>
        <div className="validator-cards">{(ledger?.validators || system?.ledger.validators || []).map(v => <div className="panel" key={v.validator_id}><div className="validator-icon"><Database size={20}/></div><strong>{v.validator_id}</strong><Badge value={v.status}/><small>Height {v.height ?? "—"}</small></div>)}</div>
      </>}
      {activeRoute === "system" && <><PageTitle eyebrow={HOSTED_DEMO ? "HOSTED DEMONSTRATION" : "LOCAL DEPLOYMENT"} title="System status" description={HOSTED_DEMO ? "Live checks from the hosted API and three logical validator stores. Data may reset when the demo service restarts." : "Live checks from the local API and three validator stores. The runtime does not call a cloud service."}/><div className="status-summary"><div><span className="pulse"/><strong>{HOSTED_DEMO ? "DEPLOYMENT MODE" : "AIR-GAPPED MODE"}</strong><span>{HOSTED_DEMO ? system?.deployment_mode : system?.air_gapped_mode || "UNAVAILABLE"}</span></div><div><strong>External runtime dependencies</strong><span>{system?.runtime_external_dependencies ?? "—"}</span></div><div><strong>Validator quorum</strong><span>{system?.ledger.quorum ?? "—"}/3</span></div></div><div className="system-grid">{[["Backend API", error ? "ERROR" : "READY"], ["Post-quantum engine", system?.pqc_engine], ["Watermark engine", system?.watermark_engine], ["Application database", system?.database], ["Ledger chain", system?.ledger.status], ["Outbound isolation test", system?.egress_test]].map(([label, value]) => <div className="panel system-card" key={label}><span>{label}</span><Badge value={value}/></div>)}</div><section className="panel"><div className="panel-head"><div><span className="eyebrow">VALIDATOR NETWORK</span><h3>Three independent local stores</h3></div><button className="text-button" onClick={() => void refresh()}><RefreshCw size={15}/> Recheck</button></div><div className="validator-list">{(system?.ledger.validators || []).map(v => <div key={v.validator_id}><span className={`node-dot ${tone(v.status)}`}/><span>{v.validator_id}</span><Badge value={v.status}/></div>)}</div><div className="panel-foot"><span>Version {system?.app_version || "—"}</span><span>Standards-based research prototype</span></div></section>{(system?.pqc_error || system?.watermark_error) && <div className="alert error">{system.pqc_error || system.watermark_error}</div>}</>}
      {activeRoute === "help" && <><PageTitle eyebrow="GUIDANCE & ACCESSIBILITY" title="Help and website information" description="This prototype demonstrates technical attribution of a decrypted copy. It does not determine guilt or establish legal responsibility."/><div className="two-column"><section className="panel"><h3>Three-minute walkthrough</h3><ol className="help-list"><li>Sign in as sender and distribute the seeded synthetic PDF to three recipients.</li><li>Sign out, then sign in as REC-002 and open Decrypt.</li><li>Decrypt and download the marked PDF.</li><li>Sign in as investigator and upload that downloaded copy.</li><li>Inspect the watermark match, signature, block and quorum.</li><li>Sign in as auditor and run the demonstration-only tamper test.</li></ol><a className="button secondary" href={`${API}/demo/sample-pdf`} target="_blank" rel="noreferrer">Open synthetic sample PDF <ArrowRight size={16}/></a></section><section className="panel"><h3>Accessibility</h3><p>Use keyboard navigation, the Skip to main content link, text size and contrast controls in the top strip. Major navigation labels are available in Hindi using the local translation dictionary.</p><h3>Website policies</h3><p>No external analytics, fonts, cloud identity or third-party APIs are used by the app. Uploaded material is stored in the current demo environment. Hosted storage is temporary. Use synthetic demonstration documents only.</p><h3>Contact & feedback</h3><p>This is an SIH hackathon prototype. For feedback, contact the project team running the demo directly. No online form or external transmission is configured.</p></section></div><section className="panel sitemap"><h3>Sitemap</h3><div>{routes.filter(r => allowedRoutes.includes(r.key)).map(r => <button key={r.key} onClick={() => go(r.href)}>{r.en} <ChevronRight size={15}/></button>)}</div></section></>}
    </main>
    <footer className="footer"><div className="container footer-main"><div><div className="footer-title"><ShieldCheck size={21}/> SourceX</div><p>SIH26237 · Standards-based research prototype<br/>Not an official Ministry of Defence deployment.</p></div><div><strong>Quick links</strong><button onClick={() => go("/help")}>Help</button><button onClick={() => go("/help")}>Accessibility</button><button onClick={() => go("/help")}>Sitemap</button></div><div><strong>System</strong><span>{HOSTED_DEMO ? "Hosted demo · temporary data" : "Local-only runtime"}</span><span>Last updated: 01 Oct 2026</span><span>Version {system?.app_version || "0.1.0"}</span></div></div><div className="container footer-bottom">Prototype uses fictional identities and synthetic documents. Do not upload classified material.</div></footer>
  </div>;
}

function PageTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>; }
function Evidence({ label, value, detail }: { label: string; value?: string; detail?: string }) { return <div className="evidence"><span>{label}</span><strong>{value || "—"}</strong>{detail && <small>{detail}</small>}</div>; }
export { AppShell };
